import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Link } from '@/components/common/Link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <Link href={`/stacks/${1}/companies`}>stacks/1/companies</Link>
      </main>
    </div>
  )
}
